language: python
python:
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"  # 3.10 development branch
  - "nightly"  # nightly build

install:
  - pip install zc.buildout==2.13.3
  - pip install virtualenv
  - buildout

script:
  - bin/pytest
